language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO=1.8.5

before_install:
  - export PYTHONPATH=$HOME/builds/Tervel/ifb299-property-management.git
  - export PIP_USE_MIRRORS=true
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet

script:
  - "cd property_management && python manage.py test"